# Generated by Django 3.2.3 on 2021-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
