# Generated by Django 3.2.3 on 2021-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0010_breath'),
    ]

    operations = [
        migrations.AddField(
            model_name='breath',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='order_num',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
