# Generated by Django 3.2.3 on 2021-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0011_auto_20210602_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breath',
            name='thumbnail',
            field=models.ImageField(default='breaths/placeholder.png', upload_to='breaths'),
        ),
    ]
