# Generated by Django 3.2.3 on 2021-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0012_alter_breath_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='breath',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
