# Generated by Django 3.2.3 on 2021-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0016_alter_breath_breath_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.ImageField(blank=True, default='posts/placeholder.png', null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='posts/thumbnails/placeholder.png', null=True, upload_to='posts/thumbnails'),
        ),
    ]
