# Generated by Django 3.2.3 on 2021-06-06 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0017_auto_20210606_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='theme',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
