# Generated by Django 3.2.3 on 2021-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0020_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.ImageField(blank=True, default='posts/backgrounds/placeholder.png', null=True, upload_to='posts/backgrounds'),
        ),
    ]
